name: Build appx
on:
  workflow_dispatch: {}
  push: {}

env:
  project_name: LumbarPunctureMR

jobs:
  activation:
    name: Build appx
    runs-on: windows-2019
    steps:
#    - name: Download Artifact
#      uses: actions/download-artifact@v1
#      with:
#       name: LumbarPunctureMR-Hololens2
#       path: ./
    - uses: microsoft/setup-msbuild@v1.1
    - run: curl -L https://www.dropbox.com/s/sfoc8dkllc3lsnw/Builds.zip?dl=0 --output a.zip && unzip a.zip
    - working-directory: Builds
      run: msbuild /m /t:build /p:Configuration=Release /p:Platform=ARM64
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
       name: ${{ env.project_name }}-Hololens2-AppX
       path: Builds/AppPackages