name: Build appx
on:
  workflow_dispatch: {}
  push: {}
jobs:
  activation:
    name: Build appx
    runs-on: windows-2019
    steps:
#    - name: Download Artifact
#      uses: actions/download-artifact@v1
#      with:
#       name: LumbarPunctureMR-Hololens2
#       path: ./
    - uses: microsoft/setup-msbuild@v1.1
    - run: curl -L https://www.dropbox.com/s/sfoc8dkllc3lsnw/Builds.zip?dl=0 --output a.zip && unzip a.zip
    - working-directory: LumbarPunctureMR-Hololens2
      run: msbuild .
#    - name: Restore dependencies
#      working-directory: LumbarPunctureMR-Hololens2
#      run: dotnet restore
#    - name: Build
#      working-directory: LumbarPunctureMR-Hololens2
#      run: dotnet build --no-restore
#    - name: Test
#      working-directory: LumbarPunctureMR-Hololens2
#      run: dotnet test --no-build --verbosity normal