name: Build appx
on:
  workflow_dispatch: {}
  push: {}
jobs:
  activation:
    name: Build appx
    runs-on: windows-2019
#    runs-on: ubuntu-latest
#    container: unityci/editor:windows-2020.3.26f1-windows-il2cpp-0.17.2
    steps:
      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install unity-hub --no-progress -y
      #    - name: Download Artifact
      #      uses: actions/download-artifact@v1
      #      with:
      #       name: LumbarPunctureMR-Hololens2
      #       path: ./
      - uses: microsoft/setup-msbuild@v1.1
#      - run: curl -L https://www.dropbox.com/s/lzdnlnu8rmhkn24/LumbarPunctureMR-Hololens2.zip?dl=0 --output a.zip && unzip a.zip
#      - working-directory: LumbarPunctureMR-Hololens2
#        run: msbuild .
      - run: cat "C:\Program Files\Unity\Hub\Editor\2020.3.26f1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\il2cpp\ARM\Debug\baselib.dll"